# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c_table_Avatar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_table_pb2 as common__table__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63_table_Avatar.proto\x12\x05Table\x1a\x12\x63ommon_table.proto\"q\n\x06\x41VATAR\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x32\n\tbody_type\x18\x03 \x01(\x0e\x32\x0f.Table.BodyType:\x0e\x42ODY_TYPE_NONE\x12\x19\n\x04\x61\x61\x62\x62\x18\x04 \x01(\x0b\x32\x0b.Table.AABB\"+\n\x0c\x41VATAR_ARRAY\x12\x1b\n\x04rows\x18\x01 \x03(\x0b\x32\r.Table.AVATAR')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c_table_Avatar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AVATAR._serialized_start=51
  _AVATAR._serialized_end=164
  _AVATAR_ARRAY._serialized_start=166
  _AVATAR_ARRAY._serialized_end=209
# @@protoc_insertion_point(module_scope)
