# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_table.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon_table.proto\x12\x05Table\";\n\x04\x41\x41\x42\x42\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02*Q\n\x08\x42odyType\x12\x12\n\x0e\x42ODY_TYPE_NONE\x10\x00\x12\x0f\n\x0b\x42ODY_TYPE_M\x10\x01\x12\x0f\n\x0b\x42ODY_TYPE_F\x10\x02\x12\x0f\n\x0b\x42ODY_TYPE_C\x10\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_table_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BODYTYPE._serialized_start=90
  _BODYTYPE._serialized_end=171
  _AABB._serialized_start=29
  _AABB._serialized_end=88
# @@protoc_insertion_point(module_scope)
